# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-12 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200312_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', upload_to='images/', width_field='width_field'),
        ),
    ]
