# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-12 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200312_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_auction_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
